version: '3.9'
networks:
  movie-reviews:
    driver: bridge
    name: movie-reviews
services:
  db:
    image: "postgres:15"
    container_name: "postgres-movie-reviews"
    environment:
      - POSTGRES_USER=greg
      - POSTGRES_PASSWORD=greg
      - POSTGRES_DB=movie-reviews-db
    ports:
      - "5432:5432"
    networks:
      - movie-reviews

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - movie-reviews

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "local_movie:1:1"
    networks:
      - movie-reviews

  kafka-gui:
    image: tchiotludo/akhq
    depends_on:
      - kafka
    ports:
      - "8000:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9093"
                request.timeout.ms: 60000
    networks:
      - movie-reviews