version: '3.9'
networks:
  movie-reviews:
    driver: bridge
    name: movie-reviews
services:
  db:
    image: "postgres:15"
    container_name: "postgres-movie-reviews"
    environment:
      - POSTGRES_USER=greg
      - POSTGRES_PASSWORD=greg
      - POSTGRES_DB=movie-reviews-db
    ports:
      - "5432:5432"
    networks:
      - movie-reviews

#  zookeeper:
#    image: zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    networks:
#      - movie-reviews

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
#    depends_on:
#      - zookeeper
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "local_movie:1:1"

    networks:
      - movie-reviews

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
#    command: "sh -c 'cub kafka-ready -b localhost:9092 1 20 && kafka-topics --create --topic local_movie --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server localhost:9092'"
    networks:
      - movie-reviews

  kafka-gui:
    image: tchiotludo/akhq
    depends_on:
      - kafka1
    ports:
      - "8000:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:29092"
                request.timeout.ms: 60000
    networks:
      - movie-reviews