databaseChangeLog:
  - changeSet:
      id: 001_init_schema
      author: gpeterschmitt
      changes:
        - createTable:
            tableName: movie
            columns:
              - column:
                  name: movie_id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: title
                  type: varchar(40)
                  constraints:
                    nullable: false
              - column:
                  name: review
                  type: text
        - createTable:
            tableName: review
            columns:
              - column:
                  name: review_id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: author
                  type: varchar(40)
                  constraints:
                    nullable: false
              - column:
                  name: review_body
                  type: text
#        - addForeignKeyConstraint:
#            baseTableName: review
#            baseColumnNames: review_id
#            referencedTableName: movie
#            referencedColumnNames: movie_id
#            onDelete: CASCADE
#            constraintName: fk_movie_review
        -  createSequence:
             cacheSize:  371717
             catalogName:  movie
             cycle:  false
             dataType:  int
             incrementBy:  1
             maxValue:  100
             minValue:  1
             schemaName:  public
             sequenceName:  movie_seq
             startValue:  1
