databaseChangeLog:
  - changeSet:
      id: 001_init_schema
      author: gpeterschmitt
      changes:
        - createTable:
            tableName: movie
            columns:
              - column:
                  name: movie_id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: title
                  type: varchar(40)
                  constraints:
                    nullable: false
              - column:
                  name: review
                  type: text
                  constraints:
        - createTable:
            tableName: review
            columns:
              - column:
                  name: review_id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: author
                  type: varchar(40)
                  constraints:
                    nullable: false
              - column:
                  name: review_body
                  type: text
                  constraints:
                    nullable: false
#        - addForeignKeyConstraint:
#            baseTableName: review
#            baseColumnNames: review_id
#            referencedTableName: movie
#            referencedColumnNames: movie_id
#            onDelete: CASCADE
#            constraintName: fk_movie_review
